on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Go
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Install Go
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
    - name: Test
      run: go test ./...
